### ISSUE TITLE
Widgets in Tkinter beschreiben

### ISSUE THREAD

**Issue by fog1992** [Informatik-HS-KL/Python-Tutorial#1]
Beschreiben wie GUIs in Python mit Tk bzw. Tkinter erstellt werden.
Beispiele erstellen.
[Python Wiki TkInter](https://wiki.python.org/moin/TkInter)

Kapitel: Benutzeroberflächen

**Comment by Chriseibel** [comment]
Widgets fertig beschrieben, Issue geschlossen.
