### ISSUE TITLE
Elementare Datentypen 

### ISSUE THREAD

**Issue by fog1992** [Informatik-HS-KL/Python-Tutorial#2]
Es sollen die elementaren Datentypen in Python incl. Strings beschrieben werden.

- [x] Zahlen
- [x] Zeichenketten
- [x] Null / None
- [x] Referenz / Identität / Kopie (kann auch zu Objekte und Klassen)

Kapitel: Datentypen

**Comment by MLohmueller** [comment]
Hallo, anbei das PFD mit den Anmerkungen
An die unklaren Sachen hab ich ein Fragezeichen gemacht. Ich habe die Korrekturen NICHT in den Text eingefügt, weil ihr am besten selbst drüber schaut. LG Miriam
[Korr. 14.11.2018_Ele.Daten_Kontr_MaschL.pdf](https://github.com/Informatik-HS-KL/Python-Tutorial/files/2580079/Korr.14.11.2018_Ele.Daten_Kontr_MaschL.pdf)
