### ISSUE TITLE
Kontrollstrukturen

### ISSUE THREAD

**Issue by fog1992** [Informatik-HS-KL/Python-Tutorial#3]
Es sollen die verschiedenen Kontrollstrukturen in Python werden.

- [x] Verzweigungen
- [x] Schleifen (Zählschleifen / bedingte Wiederholungen)
- [x] logische Operatoren

Beispiele erstellen.

Kapitel: Grundlagen

**Comment by MLohmueller** [comment]
Hallo, anbei das PFD mit den Anmerkungen
An die unklaren Sachen hab ich ein Fragezeichen gemacht. Ich habe die Korrekturen NICHT in den Text eingefügt, weil ihr am besten selbst drüber schaut. LG Miriam
[Korr. 14.11.2018_Ele.Daten_Kontr_MaschL.pdf](https://github.com/Informatik-HS-KL/Python-Tutorial/files/2580077/Korr.14.11.2018_Ele.Daten_Kontr_MaschL.pdf)
