### ISSUE TITLE
Hervorheben/Betonen von Wörtern

### ISSUE THREAD

**Issue by GesunderApfel** [Informatik-HS-KL/Python-Tutorial#30]
In der Vorlesung haben wir uns darauf geeinigt Schlüsselwörter mit dem "inline"-Befehl zu markieren.
Schlüsselwörter verstehe ich hier als Teil des Codes bzw. der Programmiersprache(n).

Bspw. die Wörter Exception, None/Null, Variablennamen etc.

Ich möchte aber an kritischen Stellen Wörter betonen, um ein gewisses "Konzept" oder eine Kerninformaton zu vermitteln.

Bsp: Vorgang A ist _schneller_ als Vorgang B.

Mein Vorschlag wäre es in solchen Fällen kursiv zu schreiben.
Würden wir hier die gleiche Art von Betonung benutzen, führt das eventuell zur Verwirrung.

**Comment by MBrill** [comment]
Ja, auf jeden Fall würde ich das mit \emph{} hervorheben.

Quelltexte oder Variablennamen schreiben wir mit \lstinlne$$ - als Beispiel: \lstinline$class$. Das erhält dann den gleichen Font wie die Listinsg.
