### ISSUE TITLE
Kapitel Grundlagen zusammenführen

### ISSUE THREAD

**Issue by fog1992** [Informatik-HS-KL/Python-Tutorial#46]
### Die Themen im Kapitel zu einem ganzen zusammenführen

- [ ] Übergänge im Kapitel vereinheitlichen
- [x] Reihenfolge abstimmen
- [ ] Übungen abstimmen

Zugehörige Issues: #17 , #3 , #6, #2

**Comment by fog1992** [comment]
Es sollte auch abgestimmt werden, ob es pro Abschnitt eine Zusammenfassung gibt oder am Ende des Kapitels eine.

**Comment by RobinGuth** [comment]
Wir haben uns darauf geeignigt, eine große Zusammenfassung für die gesamten Grundlagen zu schreiben.

**Comment by RobinGuth** [comment]
@Jub42  @ansc0098 Bitte setzt euch mit mir oder @fraygeyst in Verbindung, damit wir besprechen können, wie die Zusammenfassung für eueren Abschnitt erstellt werden soll.

**Comment by ansc0098** [comment]
@RobinGuth @fraygeyst  Zu #6 existiert eine Zusammenfassung in dem Kapitel. Diese kann genutzt werden um eine "große Zusammenfassung" für das Grundlagenkapitel zu schreiben. Anschließend  sollte die Zusammenfassung aus #6 rausgelöscht werden?!

**Comment by fraygeyst** [comment]
@ansc0098 Die Zusammenfassungs-Datei ist nun im Master. Ihr könnt eure eigene Zusammenfassung dort jetzt einfügen.

**Comment by RobinGuth** [comment]
Ich werde den Rest der Zusammenfassung zusammenführen und nochmal überprüfen ob das ganze zusammenpasst. Ich werde anschließend nochmal schauen ob uns irgendwo Übungen fehlen.

**Comment by RobinGuth** [comment]
Done
