### ISSUE TITLE
Iterator in Python

### ISSUE THREAD

**Issue by Jub42** [Informatik-HS-KL/Python-Tutorial#56]
Iterator in Python beschreiben.
Beispiele erstellen.

- [x] Iteratoren

Kapitel: Kontrollstrukturen #3

**Comment by RobinGuth** [comment]
Braucht ihr noch Unterstützung bei dieser Issue?

**Comment by RobinGuth** [comment]
In Absprache mit den anderen Teammitgliedern werde ich diese Issue übernehmen.

**Comment by RobinGuth** [comment]
Done.
