### ISSUE TITLE
Labels von Gleitobjekten

### ISSUE THREAD

**Issue by MBrill** [Informatik-HS-KL/Python-Tutorial#62]
Wir haben am 3. 1. in der Diskussion bemerkt, dass wir eine Regel benötigen, wo im LaTeX-Quelltext die Labels für Abbildungen und Tabellen gesetzt werden. Abhängig davon, wo das Label im Quelltext steht werden im Acrobat Reader unterschiedliche Sprungziele eingestellt.

Möglich ist es, das Label direkt nach begin{figure} oder begin{table} zu setzen. Eine Alternative ist, das Label innerhalb der Caption einzutragen, also so etwas wie \caption{\label[xxx}xxx}.

- Die Entscheidung wird am Donnerstag, 10. Januar fallen.
- Anschließend müssen wir unsere kompletten Quelltexte durchgehen und anpassen.

**Comment by MBrill** [comment]
Wir konnten keine endgültige Entscheidung herbeiführen. Wir werden dies weiter untersuchen. Bis auf weiteres legen wir die labels in die caption oder danach.

**Comment by fog1992** [comment]
Die Lösung für das Problem ist beim `package caption `die Option `hypcap=true` zu setzen.

Baue ich in die Setup-Datei ein.


Siehe auch [stachexchange](https://tex.stackexchange.com/questions/27096/href-to-an-image-label-how-to-jump-to-the-image-instead-of-the-caption-below-t)

**Comment by fog1992** [comment]
Ab Version 3.1 von `\caption` wird die Option hypcap nicht mehr benötigt. caption hat ab dieser Version eine eigene Lösung für das Problem.

> Das hypcap-Paket[11] bietet eine Lösung zu dem Problem an, daß Hyperlinks auf Gleitumgebungen nicht auf die Abbildung bzw. Tabelle verweisen, sondern stattdessen auf die Beschriftung. Die Version 3.1 des caption-Paketes löst dieses Problem bereits auf seine eigene Art und Weise, so daß das hypcap-Paket in der Regel nicht mehr zusätzlich benötigt wird.

- [doc caption](https://mirror.reismil.ch/CTAN/macros/latex/contrib/caption/caption-deu.pdf)
- [doc hypcap](http://texdoc.net/texmf-dist/doc/latex/oberdiek/hypcap.pdf)
