### ISSUE TITLE
Probleme beim Pullen

### ISSUE THREAD

**Issue by MHaselmaier** [Informatik-HS-KL/Python-Tutorial#85]
Ich  habe eben den aktuellen Stand gepullt.
Es befindet sich im Ordner chapter einmal die Datei InputOutput.tex und die Datei inputOutput.tex.
Dies führt bei mir zu Problemen.
Lokal wird mit nur die Datei mit kleinem i angezeigt und ich kann die Datei mit großem I nicht erzeugen.
Laut Windows existiert diese Datei bereits.

Ich habe flüchtig gesehen, dass @fog1992 diese beiden Dateien in einem Pullrequest bereits angesprochen hat.
Das sollte am besten schnell behoben werden.
Aktuell kann ich nicht zwischen meinen lokale Branches wechseln, da ich "nicht commitete Änderungen habe".
Ich kann sie allerdings auch nicht stashen.
So kann ich an meinem Teil nicht weiterarbeit!

**Comment by MHaselmaier** [comment]
Das hier ist der Pull request, in dem die beiden Dateien angesprochen wurden.
https://github.com/Informatik-HS-KL/Python-Tutorial/pull/75

**Comment by fog1992** [comment]
Ich schaue ich mir direkt an

**Comment by MHaselmaier** [comment]
Falls jemand das selbe Problem hat:
Man kann immer noch Branches wechseln wenn man es forced:
git checkout -f <local branch>

**Comment by fog1992** [comment]
Da habe ich wohl beim Merge was übersehen. Sollte jetzt behoben sein. Bitte um Bestätigung :)

**Comment by MHaselmaier** [comment]
Super, funktioniert wieder alles!
Vielen Dank für die schnell Reaktion :)
